export const LOADING_BEGIN = 'LOADING_BEGIN';
export const LOADING_END = 'LOADING_END';
export const SIGN_OUT = 'SIGN_OUT';
export const SIGN_UP_REQUEST = 'SIGN_UP_REQUEST';
export const SIGN_UP_SUCCESS = 'SIGN_UP_SUCCESS';
export const SIGN_UP_FAILURE = 'SIGN_UP_FAILURE';

export const SIGN_IN_REQUEST = 'SIGN_IN_REQUEST';
export const SIGN_IN_SUCCESS = 'SIGN_IN_SUCCESS';
export const SIGN_IN_FAILURE = 'SIGN_IN_FAILURE';

export const PROPERTIES_REQUEST = 'PROPERTIES_REQUEST';
export const PROPERTIES_SUCCESS = 'PROPERTIES_SUCCESS';
export const PROPERTIES_FAILURE = 'PROPERTIES_FAILURE';

export const CITIES_REQUEST = 'CITIES_REQUEST';
export const CITIES_SUCCESS = 'CITIES_SUCCESS';
export const CITIES_FAILURE = 'CITIES_FAILURE';

export const PROPERTY_TYPES_REQUEST = 'PROPERTY_TYPES_REQUEST';
export const PROPERTY_TYPES_SUCCESS = 'PROPERTY_TYPES_SUCCESS';
export const PROPERTY_TYPES_FAILURE = 'PROPERTY_TYPES_FAILURE';

export const PROPERTY_BOOKING_REQUEST = 'PROPERTY_BOOKING_REQUEST';
export const PROPERTY_BOOKING_SUCCESS = 'PROPERTY_BOOKING_SUCCESS';
export const PROPERTY_BOOKING_FAILURE = 'PROPERTY_BOOKING_FAILURE';

export const CAR_BOOKING_REQUEST = 'CAR_BOOKING_REQUEST';
export const CAR_BOOKING_SUCCESS = 'CAR_BOOKING_SUCCESS';
export const CAR_BOOKING_FAILURE = 'CAR_BOOKING_FAILURE';

export const MY_BOOKING_PROPERTIES_REQUEST = 'MY_BOOKING_PROPERTIES_REQUEST';
export const MY_BOOKING_PROPERTIES_SUCCESS = 'MY_BOOKING_PROPERTIES_SUCCESS';
export const MY_BOOKING_PROPERTIES_FAILURE = 'MY_BOOKING_PROPERTIES_FAILURE';

export const SET_LANGUAGE = 'SET_LANGUAGE';

export const CARS_REQUEST = 'CARS_REQUEST';
export const CARS_SUCCESS = 'CARS_SUCCESS';
export const CARS_FAILURE = 'CARS_FAILURE';

export const MY_BOOKING_CARS_REQUEST = 'MY_BOOKING_CARS_REQUEST';
export const MY_BOOKING_CARS_SUCCESS = 'MY_BOOKING_CARS_SUCCESS';
export const MY_BOOKING_CARS_FAILURE = 'MY_BOOKING_CARS_FAILURE';


export const UPDATE_ACCOUNT_REQUEST = 'UPDATE_ACCOUNT_REQUEST';
export const UPDATE_ACCOUNT_SUCCESS = 'UPDATE_ACCOUNT_SUCCESS';
export const UPDATE_ACCOUNT_FAILURE = 'UPDATE_ACCOUNT_FAILURE';
